name: Meteobot Scheduler

on:
  schedule:
    - cron: '0 7 * * *'  # Exécuter tous les jours à 07:00 UTC
  workflow_dispatch:  # Permet d'exécuter manuellement depuis l'interface GitHub

jobs:
  run_meteobot:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Étape 4 : Exécuter le script
      - name: Run Meteobot Script
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          CITY: ${{ secrets.CITY }}
        run: |
          python meteobot.py
